### PR TITLE
Fix build by switching to golang:1.17-alpine3.13

### PR DESCRIPTION
**Pull request by vytautas-karpavicius**
**What changed?**
Use different golang:1.17 variant that is based on alpine3.13 instead.
The newer version (3.14) broke our build with `Operation not permitted` errors.
Others are having similar issues: https://github.com/docker-library/php/issues/1177

**Why?**
master build is failing after #4632

**How did you test it?**
`docker build .`

**Potential risks**

**Release notes**

**Documentation Changes**

### CODE REVIEW

**Comment by wenerme** [comment]
You better upgrade docker instead.

**Comment by longquanzheng** [comment]
> You better upgrade docker instead.

Thanks for looking @wenerme 
I didn't look at lots of the context. The build does work for me as I am using the newer version. 
Do you any cons if using this `alpine3.13` in the PR?

**Comment by wenerme** [comment]
No obviously cons, but it's always better to use newer version, beside, alpine is about to release 3.15.

**Comment by longquanzheng** [comment]
> No obviously cons, but it's always better to use newer version, beside, alpine is about to release 3.15.

Actually not just issue for local docker build, the master image releasing pipeline is also broken:
https://buildkite.com/uberopensource/cadence-server/builds/12484#7b0314ab-02c0-4231-bf50-0d1c62a176b4

I just approved it and let it go through. We can have a ticket to improve it later on.

**Pull request merged**
