### PR TITLE
CLI: make show,list workflow looks better

### PR DESCRIPTION
**Pull request by vancexu**
1. Add color 2. remove datetime by default, can add using -pdt (print date time) flag

screen shot 2018-03-12 at 11 45 29 am
screen shot 2018-03-12 at 11 42 38 am

### CODE REVIEW

**Comment by vancexu** [comment]
Change list cmd default to print one page (default 10 items)
Output in table and color
screen shot 2018-03-12 at 4 27 22 pm
screen shot 2018-03-12 at 4 27 37 pm

**Comment by mfateev** [comment]
I think for the list we want to print one page per default. But if flag is specified just stream all the pages (with appropriate throttling). But if someone does

cadence workflow list -m|more

then block pagination when buffer is full. See http://www.pixelbeat.org/programming/stdio_buffering/

**Comment by mfateev** [comment]
Can we use shorter timestamps by default?

**Comment by vancexu** [comment]
@mfateev I see what you mean. Note currently open/close worklfows can not be grabbed as stream, but as page. 
The major difference between what you describe and my currently implementation is:  you have a stream somewhere and then a "big" buffer so user can see a lot items each time they press button; but my is some number of items in one page (default 10), and user may need to press many times.
I can change the -m mode default using large page size 100, but then user cannot use their own page size (with -pagesize flag) for more mode. How does this sound to you? I personally prefer the current way

For shorter timestamps, what's your proposal? only time without date? I agree them take spaces but have not better way to deal with it.

**Comment by vancexu** [comment]
Add command `listall`, so that user can use pipe or redirect like`cadence workflow listall | more`

**Pull request merged**
