### PR TITLE
Make Postgres plugin update all fields on upsert collision.

### PR DESCRIPTION
**Pull request by chris-rcn**
Fixes issue #3482.

After an upsert collision, all fields should be updated (as if the row was newly inserted).
Example rendered SQL before:
```
INSERT INTO activity_info_maps (shard_id, domain_id, workflow_id, run_id, schedule_id, data,data_encoding,last_heartbeat_details,last_heartbeat_updated_time)
VALUES (:shard_id, :domain_id, :workflow_id, :run_id, :schedule_id, :data,:data_encoding,:last_heartbeat_details,:last_heartbeat_updated_time)
ON CONFLICT (shard_id, domain_id, workflow_id, run_id, schedule_id) DO UPDATE
SET shard_id = excluded.shard_id, domain_id = excluded.domain_id, workflow_id = excluded.workflow_id, run_id = excluded.run_id, schedule_id = excluded.schedule_id
```
After:
```
INSERT INTO activity_info_maps (shard_id, domain_id, workflow_id, run_id, schedule_id, data,data_encoding,last_heartbeat_details,last_heartbeat_updated_time)
VALUES (:shard_id, :domain_id, :workflow_id, :run_id, :schedule_id, :data,:data_encoding,:last_heartbeat_details,:last_heartbeat_updated_time)
ON CONFLICT (shard_id, domain_id, workflow_id, run_id, schedule_id) DO UPDATE
SET (shard_id, domain_id, workflow_id, run_id, schedule_id, data,data_encoding,last_heartbeat_details,last_heartbeat_updated_time)
= (:shard_id, :domain_id, :workflow_id, :run_id, :schedule_id, :data,:data_encoding,:last_heartbeat_details,:last_heartbeat_updated_time)
```
For comparison, here is the MySQL template:
```
REPLACE INTO %[1]v
(shard_id, domain_id, workflow_id, run_id, %[4]v, %[2]v)
VALUES
(:shard_id, :domain_id, :workflow_id, :run_id, :%[4]v, %[3]v)
```

Previously, the Postgres plugin was not updating all data when it should have.
See linked issue for repro case.

I have tested locally and in our staging environment.

Worst case:  Could introduce new bugs in the Postgres plugin.

### CODE REVIEW

**Comment by chris-rcn** [comment]
@longquanzheng Would you mind taking a look?

**Comment by longquanzheng** [comment]
> @longquanzheng Would you mind taking a look?

Thanks for fixing it. Seems like I missed the field.

**Comment by chris-rcn** [comment]
@anish531213 Is this blocked on something?  Do I need to do anything?

**Comment by longquanzheng** [comment]
@chris-rcn seems like the tests are not passing. Would you mind I take over to fix it?

**Comment by chris-rcn** [comment]
Not at all.  Be my guest.  Thank you!

**Comment by chris-rcn** [comment]
I think that there might be a problem when trying to upset more than one activity at a time.

**Comment by chris-rcn** [comment]
@anish531213 Did you find anything?  It seems like sqlx isn't handling the multi-row args to NamedExec.

**Comment by longquanzheng** [comment]
> I think that there might be a problem when trying to upsert more than one activity at a time.

Your investigation is correct. The postgres support in Sqlx library is very bad. I have a workaround here: https://github.com/uber/cadence/pull/3498

**Comment by chris-rcn** [comment]
Awesome!  Closing in favor of #3498.

**Pull request closed without merging**
