### PR TITLE
Propose adding SQL database support

### PR DESCRIPTION
**Pull request by ryanwalls**
We figured we would start with a proposal before starting implementation.  Please feel free to suggest edits.  Once everyone is happy with the proposal, we can merge this PR and then it becomes the template for our implementation.

### CODE REVIEW

**Comment by ryanwalls** [comment]
@mfateev @samarabbas Any news on the SQL implementation?  We have some roadmap items that depend on this change.  We submitted this proposal and are happy to commit engineering resources, but @meiliang86 mentioned in this comment https://github.com/uber/cadence/issues/439#issuecomment-397124821 that the uber team was going to work on it.  I haven't seen any changes in the mysql branch for a few weeks.  https://github.com/uber-qlam/cadence/tree/mysql.  Can you give us an approximate timeline so we can update our deliverables?  We really wanted to get the SQL version working by the end of July.  If you could use more resources, let us know.

**Comment by meiliang86** [comment]
@ryanwalls We just closed the overall design and @uber-qlam is working on the implementation for mySQL. We estimate that it would take 4-6 wks for the initial implementation. @uber-qlam  will share the overall design doc with you guys and we can discuss further later on.

**Comment by uber-qlam** [comment]
https://docs.google.com/a/uber.com/document/d/e/2PACX-1vRClVpBxYgw50UsKaLJKIBIbBPBiQoU5BUmlymZ3vqrgKNHY7YA8rmg5sKfKdeh0xltM1kN__iePn0V/pub

Hi, here is the rough design doc. The most interesting logic is probably under the first three headings; the rest is details on the schema. Let us know if you have any concerns.

**Comment by h7kanna** [comment]
Hi team,
I am interested in contributing to this effort. 
Please let me know if any help needed ( I am willing to spend weekends on this)

Thanks,

**Comment by ryanwalls** [comment]
@uber-qlam The document above isn't accessible.  Mind making it public?

**Comment by uber-qlam** [comment]
@ryanwalls Sorry! For now, here is a PDF copy. We'll come up with a more collaborative solution at a later date.
[Cadence SQL Matching & History Persistence Schema Design.pdf](https://github.com/uber/cadence/files/2177569/Cadence.SQL.Matching.History.Persistence.Schema.Design.pdf)

**Comment by h7kanna** [comment]
Any timeline when this will land into master?
Thanks

**Comment by dmetzgar** [comment]
Hi @ryanwalls, could you put this proposal in the form of a GitHub issue? Then it's more discoverable and more likely to be maintained.

**Pull request closed without merging**
