### PR TITLE
Revert changes to use string casting for shard ID

### PR DESCRIPTION
**Pull request by yux0**
**What changed?**
Change the shard ID integer casting to use string(rune())

**Why?**
Make backward compatible with ringpop mapping.

**How did you test it?**

**Potential risks**

### CODE REVIEW

**Review by Groxx — APPROVED** [review]
Yep, looks right, all those lookups are hash-related.
That said: is it possible to change any of these funcs to take an int instead of a string?

**Comment by yux0** [comment]
> Yep, looks right, all those lookups are hash-related.
> That said: is it possible to change any of these funcs to take an int instead of a string?

We can abstract it and pass in int. But we already use this int -> char. So even in the func, we have to do int -> char -> string.

**Comment by Groxx** [comment]
Yeah, somewhere it has to happen.  I'm just hoping to take that need out of calling locations, as that kind of abnormal semantic requirement not really visible during code review.

**Review by yycptt — APPROVED** [review]

**Comment by yycptt** [comment]
> > Yep, looks right, all those lookups are hash-related.
> > That said: is it possible to change any of these funcs to take an int instead of a string?
> 
> We can abstract it and pass in int. But we already use this int -> char. So even in the func, we have to do int -> char -> string.

Yeah having a function may be a good idea. Although we still do int -> rune -> string conversion in the function, at least there's a central place for the conversion and situation where history client using a different logic than the shard controller won't happen.

**Pull request merged**
