### PR TITLE
Do not return not exists error in history pagination function

### PR DESCRIPTION
**Pull request by Shaddoll**
**What changed?**
Do not return not exists error in history pagination function

**Why?**
For a history paginator, if there is no history events, we should not return entity not exists error but stop the iteration.

**How did you test it?**

**Potential risks**

**Release notes**

**Documentation Changes**

### CODE REVIEW

**Comment by davidporter-id-au** [comment]
Can you provide a bit more detail as to this scenario? Under conditions is returning no history a valid state?

**Review by allenchen2244 — APPROVED** [review]
LGTM

**Comment by Shaddoll** [comment]
> Can you provide a bit more detail as to this scenario? Under conditions is returning no history a valid state?

@davidporter-id-au We have some helper functions iterating workflow histories. The iterator provides `HasNext()` and `Next()` functions to iterate histories. But if the workflow history doesn't exist, the first iteration of `HasNext()` doesn't return `false`, and when we call `Next()`, we get an error. I think for an iterator, this behavior is not what we want, and it actually breaks the timer resurrection checker, because when we get an EntityNotExist error, the timer tasks stops retrying

**Review by davidporter-id-au — APPROVED** [review]

**Comment by davidporter-id-au** [comment]
nice, thank you for the explanation

**Pull request merged**
