### PR TITLE
Update Slack link

### PR DESCRIPTION
**Pull request by wxing1292**
same as #2619

### CODE REVIEW

**Comment by meetchandan** [comment]
the link is still now working

**Comment by vancexu** [comment]
> the link is still now working

It is working for me, what error did you see?

**Comment by meetchandan** [comment]
Screen Shot 2020-05-01 at 11 15 06 PM
@vancexu

**Comment by meetchandan** [comment]
For https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTQyYjcxZDM2YTIxMTZkMzQ0NjgxYmI3OWY5ODhiOTliM2I5MzA4NTM4MjU4YzgzZDkwNGEzOTUzNTBlNDk3Yjc

**Comment by vancexu** [comment]
> For https://join.slack.com/t/uber-cadence/shared_invite/enQtNDczNTgxMjYxNDEzLTQyYjcxZDM2YTIxMTZkMzQ0NjgxYmI3OWY5ODhiOTliM2I5MzA4NTM4MjU4YzgzZDkwNGEzOTUzNTBlNDk3Yjc

I see.
Can you try https://join.slack.com/t/uber-cadence/shared_invite/zt-dvjoiacm-1U2UM4R4mMxKhaRogEx_OQ ?

**Pull request merged**
