### PR TITLE
CDNC-2095 Clean up json annotations in types folder

### PR DESCRIPTION
**Pull request by agautam478**
Removed all the annotations from the files inside the Types folder.

refer to CDNC-2095

test cases

NA

NA

No

### CODE REVIEW

**Comment by davidporter-id-au** [comment]
@demirkayaender if anything is relying on encoding these as JSON, this is a breaking change. Are you aware of this? 

https://go.dev/play/p/wkBxh5sRBk4

**Comment by agautam478** [comment]
> @demirkayaender if anything is relying on encoding these as JSON, this is a breaking change. Are you aware of this?
> 
> https://go.dev/play/p/wkBxh5sRBk4

We removed these under the assumption that they will never be used for encoding. Would love to double check though. @demirkayaender do you have any inputs on this?

**Comment by agautam478** [comment]
Running on dev environment for testing purposes. So far everything looks fine.

**Review by allenchen2244 — APPROVED** [review]

**Comment by taylanisikdemir** [comment]
Closing as part of old PR cleanup effort.

**Pull request closed without merging**
